name: Test 🧪

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_unit:
    name: Run unit tests 🃏
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.42
      # - uses: ArtiomTr/jest-coverage-report-action@v2
      #   with:
      #     package-manager: bun
      #     test-script: bun test:coverage
      #     annotations: failed-tests
      # TODO replace below with commented job above, blocked by Bun not yet supporting a JSON coverage reporter for the action to consume nor generate (similar: https://github.com/oven-sh/bun/issues/4099)
      - name: Install dependencies
        run: bun install
      - name: Run unit tests
        run: bun run test
